# Generated by Django 3.0.5 on 2020-05-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("contents", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="title",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="title",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
